# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- dev

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install
    npm run build --prod
  displayName: 'npm install and build'

- task: AzureStaticWebApp@0
  inputs:
    app_location: '/'
    output_location: 'dist/front-wapi'
    deployment_environment: Dev
    #production_branch: Dev
    azure_static_web_apps_api_token: '9fe89123883f79a43d88e2829be412b81bc615202788b6e430a9eb5f06e9f54b2-95747407-445c-408a-8f18-97666b4b31ef00f49084'
